<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.1.3 (Python 3.7.4 on win32)" generated="20230826 16:42:55.200" rpa="false" schemaversion="2">
<suite id="s1" name="user defained keywords with Python" source="C:\Users\suhelk\PycharmProjects\Automation\Automation\user defained keywords with Python">
<suite id="s1-s1" name="Resource Py" source="C:\Users\suhelk\PycharmProjects\Automation\Automation\user defained keywords with Python\resource_py.robot">
<test id="s1-s1-t1" name="fplder">
<kw name="folder_create">
<kw name="crete_folder">
<msg timestamp="20230826 16:42:57.209" level="FAIL">No keyword with name 'crete_folder' found.</msg>
<status status="FAIL" starttime="20230826 16:42:57.209" endtime="20230826 16:42:57.210"/>
</kw>
<status status="FAIL" starttime="20230826 16:42:57.203" endtime="20230826 16:42:57.211"/>
</kw>
<status status="FAIL" starttime="20230826 16:42:57.201" endtime="20230826 16:42:57.212">No keyword with name 'crete_folder' found.</status>
</test>
<status status="FAIL" starttime="20230826 16:42:55.395" endtime="20230826 16:42:57.213"/>
</suite>
<suite id="s1-s2" name="User Defined Keywords" source="C:\Users\suhelk\PycharmProjects\Automation\Automation\user defained keywords with Python\user_defined_keywords.robot">
<test id="s1-s2-t1" name="folder">
<kw name="folder_create">
<msg timestamp="20230826 16:42:57.305" level="FAIL">No keyword with name 'folder_create' found.</msg>
<status status="FAIL" starttime="20230826 16:42:57.305" endtime="20230826 16:42:57.305"/>
</kw>
<status status="FAIL" starttime="20230826 16:42:57.297" endtime="20230826 16:42:57.306">No keyword with name 'folder_create' found.</status>
</test>
<status status="FAIL" starttime="20230826 16:42:57.218" endtime="20230826 16:42:57.307"/>
</suite>
<status status="FAIL" starttime="20230826 16:42:55.210" endtime="20230826 16:42:57.310"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="2" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="2" skip="0" id="s1" name="user defained keywords with Python">user defained keywords with Python</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1" name="Resource Py">user defained keywords with Python.Resource Py</stat>
<stat pass="0" fail="1" skip="0" id="s1-s2" name="User Defined Keywords">user defained keywords with Python.User Defined Keywords</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20230826 16:42:57.199" level="ERROR">Error in file 'C:\Users\suhelk\PycharmProjects\Automation\Automation\user defained keywords with Python\resource_py.robot' on line 3: Test library '..\Automation\user defained keywords with Python\create folder.py' does not exist.</msg>
<msg timestamp="20230826 16:42:57.227" level="ERROR">Error in file 'C:\Users\suhelk\PycharmProjects\Automation\Automation\user defained keywords with Python\user_defined_keywords.robot' on line 3: Resource file '..\Automation\user defained keywords with Python\resource_py.robot' does not exist.</msg>
</errors>
</robot>
